src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $front_page;

    /**
     * @ORM\OneToMany(targetEntity=BookEntry::class, mappedBy="book")
     */
    private $bookEntries;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    public function __construct()
    {
        $this->bookEntries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFrontPage(): ?string
    {
        return $this->front_page;
    }

    public function setFrontPage(?string $front_page): self
    {
        $this->front_page = $front_page;

        return $this;
    }

    /**
     * @return Collection<int, BookEntry>
     */
    public function getBookEntries(): Collection
    {
        return $this->bookEntries;
    }

    public function addBookEntry(BookEntry $bookEntry): self
    {
        if (!$this->bookEntries->contains($bookEntry)) {
            $this->bookEntries[] = $bookEntry;
            $bookEntry->setBook($this);
        }

        return $this;
    }

    public function removeBookEntry(BookEntry $bookEntry): self
    {
        if ($this->bookEntries->removeElement($bookEntry)) {
            // set the owning side to null (unless already changed)
            if ($bookEntry->getBook() === $this) {
                $bookEntry->setBook(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\String\Slugger\SluggerInterface;

class SecurityController extends AbstractController
{
    // https://symfony.com/doc/current/security.html#logging-out

    private $em;

    /**
     * @param $em
     */
    public function __construct(EntityManagerInterface $em) {
        $this->em = $em;
    }

    /**
     * @Route("/app/login", name="app_login")
     */
    public function index(AuthenticationUtils $authenticationUtils): Response {

        $error = $authenticationUtils->getLastAuthenticationError();

        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/index.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error
        ]);
    }

    /**
     * @Route("/app/logout", name="app_logout", methods={"GET"})
     */
    public function logout(): void {

    }

    /**
     * @Route("/app/register", name="app_register")
     */
    public function register(Request $request, UserPasswordHasherInterface $passwordHasher, SluggerInterface $slugger) {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $photo = $form->get('photo')->getData();
            if ($photo) {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photo->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $photo->move(
                        $this->getParameter('photos_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw new \Exception('There is an error.');
                }
                $user->setPhoto($newFilename);
            }
            $raw_plass = $form->get('password')->getData();
            $hashed_pass = $passwordHasher->hashPassword($user, $raw_plass);
            $user->setPassword($hashed_pass)->setRoles(['ROLE_USER']);
            $this->em->persist($user);
            $this->em->flush();
            $this->addFlash('success', 'Que la fuerza te acompañe, te has registrado con exito, ahora, inicia sesión.');
            return $this->redirectToRoute('app_login');
        }
        return $this->render('security/register.html.twig', ['form' => $form->createView()]);
    }
}

templates/security/index.html.twig
{# templates/login/index.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
<div class="container h-100 ">
    <div class="row h-100 justify-content-center align-items-center ">

        <div class="col-md-6">
            {% if error %}
                <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}

            <form action="{{ path('app_login') }}" method="post" class="px-1 bg-white rounded my-3 p-5">

                {% for message in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}

                <div class="text-center">
                    <img src="{{asset('img/6392506.png')}}" alt="frikyland">
                    <h1 class="h3 mb-3 font-weight-normal my-5">¡Frikyland!</h1>
                </div>

                <div class="form-group">
                    <label for="username">Email:</label>
                    <input type="text" class="form-control" id="username" name="_username" value="{{ last_username }}" required autofocus />
                </div>

                <div class="form-group">
                    <label for="inputPassword">Contraseña</label>
                    <input type="password" id="password" name="_password" class="form-control" required/>
                    <input type="hidden" name="_target_path" value="/"/>
                </div>


                {# If you want to control the URL the user is redirected to on success
       <input type="hidden" name="_target_path" value="/account"/> #}

                <button class="btn btn-lg btn-block btn-success my-3" type="submit">
                    Login
                </button>

            </form>

            <a href="{{path('app_register')}}" class="btn btn-info btn-block">¿No tienes cuenta? Registrate aquí.</a>

        </div>
    </div>

{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container bg-white p-3 my-5">
        <h2 class="my-3">Registrate, nerd!</h2>
        {{form_start (form)}}
        <div class="row">
            <div class="col-md-12 my-2">
                {{form_label(form.email, 'Email*')}}
                {{form_widget(form.email, {attr:{'placeholder':'friky@example.com'}})}}
            </div>
            <div class="col-md-12 my-2">
                {{form_label(form.password, 'Password*')}}
                {{form_widget(form.password, {attr:{'placeholder':'Ingresa aquí tu contraseña'}})}}
            </div>
            <div class="col-md-12 my-2">
                {{form_label(form.password, 'Foto')}}
                {{form_widget(form.photo)}}
            </div>

            <div class="col-md-12 my-2">
                {{form_label(form.description, 'Descripción')}}
                {{form_widget(form.description, {attr:{'placeholder':'Cuentanos sobre ti'}})}}
            </div>
            <div class="col-md-12 my-2">
                {{form_widget(form.registrar, {attr:{'class':'btn btn-success btn-block'}})}}
            </div>

        </div>
        {{form_end (form)}}
        <a href="{{path('app_login')}}" class="btn btn-info btn-block">Login</a>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $('.custom-file-input').on('change', function (event) {
            var inputFile = event.currentTarget;
            $(inputFile).parent()
                .find('.custom-file-label')
                .html(inputFile.files[0].name);
        });
    </script>
{% endblock %}